### PR TITLE
use `controlName` and `experimentName` from config

### PR DESCRIPTION
**Pull request by bekzod**
not sure if this is desired feature :P, also ignoring results folder

### CODE REVIEW

**Comment by bekzod** [comment]
how to generate `phases.csv` `samples.csv` `gc.csv` files ?

**Comment by rwjblue** [comment]
Seems neat! 

@krisselden / @rondale-sc - Thoughts?

@bekzod - I think this needs a rebase now that I merged the documentation PR.

**Comment by bekzod** [comment]
@rwbelue R file still expects `phases.csv` `samples.csv` `gc.csv` should I revert this https://github.com/krisselden/ember-macro-benchmark/commit/6f7b66d2c8f1032e0721065b6f8e7c217644f0ca ?

**Comment by bekzod** [comment]
I think this is superseded by https://github.com/krisselden/ember-macro-benchmark/pull/16/files

**Comment by krisselden** [comment]
@rondale-sc was working on making this use the scripts now packaged with chrome-tracing.

**Comment by bekzod** [comment]
closing this https://github.com/krisselden/ember-macro-benchmark/pull/16/files seems to address this already

**Comment by rwjblue** [comment]
Yeah. Sorry about that y'all.

**Pull request closed without merging**
